name: Initiate GitHub Release

on:
  workflow_dispatch:
    inputs:
      pat:
        description: 'PAT'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: chandratop/monorepo-release-notes-demo
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

